#!/bin/sh

# npx -p @rollup/plugin-node-resolve

npx rollup ../all-polyfills.js -f iife -o allpolyfillsbundle-script.js  --output.name allpolyfillsbundle
npx rollup ../all-polyfills.js -f es -o allpolyfillsbundle-module.js

# makes invalid version
# npx minify allpolyfillsbundle.js > allpolyfillsbundle.min.js